# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/refs/heads/main/src/ansiblelint/schemas/ansible.json
- name: Create ls group [{{ls_group}}]
  group:
    name: "{{ ls_group }}"
    state: present

- name: generate SSH key for  [{{ ls_user }}] at "{{ssh_chroot_jail_users[0].ssh_key_filename}}"
  openssh_keypair:
    path: "~/.ssh/{{ssh_chroot_jail_users[0].ssh_key_filename}}"
    type: rsa
    size: 4096
    state: present
    force: no
  delegate_to: localhost
  become_user: "{{ local_user }}"

- name: Create ls user [{{ ls_user }}]
  user:
    name: "{{ ls_user }}"
    state: present
    groups: "{{ ls_group }}"
    append: true
    create_home: true
    shell: "{{ ssh_chroot_jail_users[0].shell }}"
  register: created_ls_user

- name: Set authorized key for ls user
  authorized_key:
    user: "{{ ls_user }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/' +  ssh_chroot_jail_users[0].ssh_key_filename + '.pub') }}"

- name: Add [{{create_user}}] to [{{ssh_chroot_jail_users[0].group}}]
  user:
    name: "{{ create_user }}"
    groups: "{{ ls_group }}"
    append: true

