---
- name: Setting working dir for bumbleflies service
  set_fact:
    docker_dir_bumbleflies: "{{ (docker.remote_dir, 'bumbleflies') | path_join }}"

- name: Configure safe directory for {{ docker_dir_bumbleflies }}/site
  git_config:
    name: safe.directory
    scope: global
    value: "{{ docker_dir_bumbleflies }}/site"
