- name: Gather bumbleflies service dir
  set_fact:
    dir_bumbleflies: "{{ (docker.services | selectattr('name', 'equalto', 'Bumbleflies') | first).dir }}"

- name: Setting working dir for bumbleflies service
  set_fact:
    docker_dir_bumbleflies: "{{ (docker.remote_dir, dir_bumbleflies ) | path_join }}"

- name: Configure safe directory for {{ docker_dir_bumbleflies }}/site
  git_config:
    name: safe.directory
    scope: global
    value: "{{ docker_dir_bumbleflies }}/site"
