- name: Setting working dir for duck service
  set_fact:
    duck_dir: "{{ (docker.remote_dir, 'duckdns' ) | path_join }}"
  tags:
    - user.dyndns.base

- import_tasks: includes/oneshot.yml
  vars:
    service:
      name : duckdns
      description: 'Dyndns update for duckdns.org'
      schedule: '00/2:30'
      command: '{{ duck_dir }}/update_duckdns.sh {{ inventory_hostname_short }} {{duck_token}}'
  tags:
    - user.dyndns.service


- name: Run dyndns
  systemd:
    scope: user
    daemon_reload: true
    name: 'duckdns.service'
    state: started
    enabled: yes
  tags:
    - user.dyndns.run
