---
extends: default

rules:
  line-length:
    max: 160
    level: warning
  indentation:
    spaces: 2
    indent-sequences: consistent
  comments:
    min-spaces-from-content: 1
  comments-indentation: {}
  document-start: disable  # Don't require --- at file start
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: false

ignore: |
  .backup/
  .cache/
  __pycache__/
  ansible/plays/vars/secrets.yml
  ansible/plays/vars/secret_*.yaml
  ansible/plays/vars/secret_*.yml
  ansible/plays/vars/ssh_jail.yaml
  ansible/plays/roles/geerlingguy.*/
  ansible/plays/roles/sebthebert.*/
  ansible/plays/roles/ls_*/
  ansible/plays/roles/user/defaults/
  ansible/plays/roles/testing/defaults/
  ansible/plays/roles/**/*.yaml  # All encrypted .yaml files
