---
container_project_name: searxng
searxng_version: latest
searxng_port: 8080
searxng_service_host: search.lehel.xyz
searxng_container_name: "{{ container_project_name }}.core"
searxng_valkey_container_name: "{{ container_project_name }}.valkey"
searxng_secret_key: "{{ vault_searxng_secret_key }}"
searxng_google_token: "{{ vault_searxng_google_token }}"
searxng_duckduckgo_token: "{{ vault_searxng_duckduckgo_token }}"
searxng_brave_token: "{{ vault_searxng_brave_token }}"
