---
container_project_name: job-search
container_home: "{{ ansible_facts['user_dir'] }}/servyy-container"
job_search_service_host: jobs.lehel.xyz
job_search_traefik_entrypoint: websecure
job_search_traefik_tls: "true"
job_search_traefik_certresolver: letsencryptdnsresolver
job_search_jwt_secret: "{{ vault_job_search_jwt_secret }}"
job_search_searxng_token: "{{ vault_searxng_brave_token }}"
job_search_searxng_url: https://search.lehel.xyz
