---
- name: Generate .env file with secrets
  template:
    src: env.j2
    dest: "{{ container_home }}/searxng/.env"
    mode: "0600"

- name: Deploy searxng services
  community.docker.docker_compose_v2:
    project_src: "{{ container_home }}/searxng"
    state: present
