- name: Check mandatory variables are defined
  assert:
    that:
      - repo_name is defined
      - key_url is defined
      - deb_url is defined
      - packages is defined
      - repository is defined
      - recheck is defined
    quiet: true

- name: Creating keyfile variable {{ repo_name }}.png
  set_fact:
    keyfile: /etc/apt/keyrings/{{ repo_name | lower | replace(' ', '_') }}.gpg
    debfile: "{{ repo_name | lower | replace(' ', '_')}}"

- name: Check keyring for {{ repo_name }}
  stat:
    path: "{{ keyfile }}"
  register: keyring_stat

- block:
    - name: Create temporary file for key
      tempfile:
        state: file
        suffix: temp
      register: temp_keyfile

    - name: Downloading [{{ repo_name }}] key from [{{ key_url }}]
      get_url:
        url: "{{ key_url }}"
        dest: "{{ temp_keyfile.path }}"
        force: true # overwrite tempfile

    - name: Create keyring for [{{ repo_name }}]
      become_user: root
      command:
        cmd: "gpg --no-default-keyring --keyring {{ keyfile }} --import {{ temp_keyfile.path }}"
        creates: "{{keyfile}}"
  when: not keyring_stat.stat.exists

- name: Add repository [{{ repo_name }}] to sources list
  become_user: root
  apt_repository:
    repo: "deb [arch=amd64 signed-by={{ keyfile }}] {{ deb_url }} {{ repository }}"
    state: present
    filename: "{{ debfile }}"
  register: added_repo

- name: Ensure no unsigned entry for [{{ repo_name }}]
  lineinfile:
    path: "{{ ('/etc', 'apt', 'sources.list.d', debfile) | path_join }}.list"
    line: "deb [arch=amd64] {{ deb_url }} {{ repository }}"
    state: absent

- name: Update cache
  become_user: root
  apt:
    update_cache: true
  when: added_repo.changed

- name: Install {{ packages }}
  become_user: root
  apt:
    name: "{{ packages }}"
    state: latest
  register: package_installed

- block:
    - name: Check [{{ repo_name }}] still present
      apt_repository:
        repo: "deb [arch=amd64 signed-by={{ keyfile }}] {{ deb_url }} {{ repository }}"
        state: present
        filename: "{{ debfile }}"

    - name: Ensure no unsigned entry for [{{ repo_name }}]
      lineinfile:
        path: "{{ ('/etc', 'apt', 'sources.list.d', debfile) | path_join }}.list"
        line: "deb [arch=amd64] {{ deb_url }} {{ repository }}"
        state: absent
  when: package_installed.changed and recheck
