- name: Setup Restic Backup Infrastructure
  hosts: all
  strategy: linear
  remote_user: "{{ create_user }}"
  become: true
  become_user: "{{ create_user }}"
  vars_files:
    - vars/default.yml
    - vars/restic.yml
    - vars/secrets.yml
  vars:
    vw_master_password: "{{ hostvars.get('localhost', {}).get('vw_master_password', '') }}"
  roles:
    - restic
  tags:
    - restic
