# Docker
- name: Clone container repository
  git:
    repo: "{{ docker.repo }}"
    dest: "{{ docker.remote_dir }}"

- name: Export local key
  command: git-crypt export-key {{ docker.local_dir }}/../{{ docker.key_file }}
  args:
    chdir: "{{ docker.local_dir }}"
    creates: "{{ docker.local_dir }}/../{{ docker.key_file }}"
  delegate_to: localhost
  become_user: "{{ local_user }}"

- name: Copy repository key to remote
  copy:
    src: "{{ docker.local_dir }}/../{{ docker.key_file }}"
    dest: "{{ docker.remote_dir }}/../{{ docker.key_file }}"

- name: Check lock state
  command: git config --local --get filter.git-crypt.smudge
  args:
    chdir: "{{ docker.remote_dir }}"
  register: lock_state
  failed_when: lock_state.stderr != ""

- name: Unlock repository
  command: git-crypt unlock "{{ docker.remote_dir }}/../{{ docker.key_file }}"
  args:
    chdir: "{{ docker.remote_dir }}"
  when: lock_state.rc != 0
