- name: Ensure Photo database has correct filemod
  file:
    path: "{{ ('docker.remote_dir', 'photoprism', 'database' | path_join ) }}"
    state: directory
    owner: "{{ create_user }}"
    group: "{{ create_user }}"
    mode: "0755"

- name: Create local .env files for docker service
  template:
    src: docker.env.j2
    dest: "{{(docker.remote_dir, item.dir, '.env') | path_join}}"
  vars:
    service_url: "{{item.dir}}.{{inventory_hostname}}.duckdns.org"
  with_items:
    - "{{ docker.services }}"