- block:
  - name: Find backup database files
    find:
      paths: "{{(backup_dir + docker.remote_dir, 'photoprism', 'database') | path_join}}"
      recurse: no
    register: backup_files

  - name: Latest backup file
    set_fact:
      newest_backup: "{{ backup_files.files | sort(attribute='mtime',reverse=true) | first }}"

  - name: Find current database files
    find:
      paths: "{{ (docker.remote_dir, 'photoprism') | path_join }}"
      recurse: no
    register: current_files

  - name: Latest current file
    set_fact:
      newest_current: "{{ current_files.files | sort(attribute='mtime',reverse=true) | first }}"

  - name: Restore photo database from backup
    copy:
      remote_src: yes
      # concatenate strings to prevent striping of first '/'
      src: "{{(backup_dir + docker.remote_dir, 'photoprism', 'database') | path_join}}"
      dest: "{{ (docker.remote_dir, 'photoprism') | path_join }}"
      owner: "{{ create_user }}"
      group: "{{ create_user }}"
      mode: "0755"
    tags:
      - user.docker.photo.restore
    when: newest_backup.mtime > newest_current.mtime
  tags:
    - user.docker.photo