# Install packages
- name: Install Prerequisites
  apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

- name: Install required system packages
  apt: name={{ sys_packages }} state=latest

# User + Key Setup
- name: Create a new regular user with sudo privileges
  user:
    name: "{{ create_user }}"
    state: present
    groups: sudo
    append: true
    create_home: true
    shell: /bin/zsh

- name: Add user "{{ create_user }}" to sudo
  lineinfile:
    path: /etc/sudoers.d/{{ create_user }}
    line: '{{ create_user }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'

- name: Set authorized key for remote user
  authorized_key:
    user: "{{ create_user }}"
    state: present
    key: "{{ copy_local_key }}"

# Mount storgabox
- name: Create credential file (used for fstab entry)
  copy:
    content: |
      username={{ storagebox_credentials.user }}
      password={{ storagebox_credentials.user }}
    dest: "{{ storagebox.file }}"
    mode: 0600

- name: Check mountpoint exist
  file:
    path: "{{ storagebox.mount }}"
    state: directory
    owner: "{{ create_user }}"
    group: "{{ create_user }}"
    mode: "0770"

- name: Create fstab entry for folder share
  mount: 
    state: present 
    fstype: cifs 
    opts: "credentials={{ storagebox.file }},iocharset=utf8,uid=1000,gid=1000" 
    src: "{{ storagebox_credentials.remote }}" 
    path: "{{ storagebox.mount }}"
