# Install packages
- name: Install Prerequisites
  apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

- name: Install required system packages
  apt: name={{ sys_packages }} state=latest

- name: Ensure a locale exists
  community.general.locale_gen:
    name: de_DE.UTF-8
    state: present