# Mount storgabox
- name: Create credential file (used for fstab entry)
  copy:
    content: |
      username={{ storagebox_credentials.user }}
      password={{ storagebox_credentials.password }}
    dest: "{{ storagebox.file }}"
    mode: 0600
  tags:
    - system.storagebox.credentials

- name: Check mountpoint exist
  file:
    path: "{{ storagebox.mount }}"
    state: directory
    owner: "{{ create_user }}"
    group: "{{ create_user }}"
    mode: "0755"
  tags:
    - system.storagebox.mount.exist

- name: Create fstab entry for folder share
  mount:
    state: present
    fstype: cifs
    opts: "credentials={{ storagebox.file }},iocharset=utf8,uid=1000,gid=1000"
    src: "{{ storagebox_credentials.remote }}"
    path: "{{ storagebox.mount }}"
  tags:
    - system.storagebox.mount.fstab

- name: Check if storagebox is already mounted
  command: '/bin/mountpoint -q {{storagebox.mount}}'
  register: storagebox_check
  failed_when: storagebox_check.stderr != ''
  changed_when: storagebox_check.rc != 0
  tags:
    - system.storagebox.mount.check

- block:
  - name: Mount storagebox
    command: mount "{{ storagebox.mount }}"
    register: storagebox_mount
    failed_when: not (storagebox_mount.rc == 0 or storagebox_mount.rc == 32) # success or operation waiting (restart required)
  - block:
    - name: Reboot when mount was unsuccessful
      reboot:

    - name: Mount storagebox (after reboot)
      command: mount "{{ storagebox.mount }}"
      register: remount
      retries: 3
      delay: 2
    when: storagebox_mount.rc == 32
  when: storagebox_check.changed
  tags:
    - system.storagebox.mount
