- name: Monitor SSHD
  template:
    src: monit.sshd.check.j2
    dest: /etc/monit/conf.d/sshd
    mode: 0640
  notify: restart monit

- name: Remove old SSHD link
  file:
    path: /etc/monit/conf-enabled/openssh-server
    state: absent
  notify: restart monit

- name: Setup logging
  template:
    src: monit.log.j2
    dest: /etc/monit/conf.d/log
    mode: 0640
  notify: restart monit

- name: Setup http (for status)
  template:
    src: monit.status.j2
    dest: /etc/monit/conf.d/status
    mode: 0640
  notify: restart monit

- name: Setup alert email
  template:
    src: monit.alert.j2
    dest: /etc/monit/conf.d/alert
    mode: 0640
  notify: restart monit

- name: Flush handlers to restart monit
  meta: flush_handlers

- name: Wait for monit port to be ready
  wait_for:
    port: 2812
    timeout: 30
  when: ansible_facts['virtualization_type'] | default('') != 'docker'

- name: Run monit status
  command: monit status
  register: monit_status
  ignore_errors: true
  changed_when: false

- name: Assert monit status is callable
  assert:
    that:
      - monit_status.rc == 0
    fail_msg: "monit status command failed"
    success_msg: "monit status command succeeded"
  when: ansible_facts['virtualization_type'] | default('') != 'docker'

- name: Check if any events where postponed (maybe mailserver error)
  find:
    paths: '/var/lib/monit/events/'
  register: filesFound
  when: ansible_facts['virtualization_type'] | default('') != 'docker'

- fail:
    msg: 'Some events where postponed'
  when:
    - ansible_facts['virtualization_type'] | default('') != 'docker'
    - filesFound.matched > 0
    - "'test' not in group_names"
