- name: set swap_file variable
  set_fact:
    swap_file: /{{ swap_space }}B.swap
  tags:
    - system.swap.file
    - system.swap.file.check
    - system.swap.file.permission
    - system.swap.file.format
    - system.swap.fstab
    - system.swap.create
    - system.swap.on
    - system.swap.swappiness

- name: check if swap file exists
  stat:
    path: "{{ swap_file }}"
  register: swap_file_check
  tags:
    - system.swap.file.check
    - system.swap.file.format
    - system.swap.on
    - system.swap.create

- name: Calculate blocks
  command: 'numfmt --from iec --format "%8.0f" {{ swap_space }}'
  register: size_int

- set_fact:
    dd_count: "{{ (size_int.stdout | int) / 1000000 }}"

- name: Create swap space
  command: dd if=/dev/zero of={{ swap_file }} bs=1M count={{dd_count|int}}
  tags:
    - system.swap.space.create
  when: not swap_file_check.stat.exists

- name: set permissions on swap file
  file:
    path: "{{ swap_file }}"
    mode: 0600
  tags:
    - system.swap.file.permission

- name: format swap file
  command: mkswap {{ swap_file }}
  when: not swap_file_check.stat.exists
  tags:
    - system.swap.file.format

- name: add to fstab
  lineinfile:
    dest: /etc/fstab
    regexp: "{{ swap_file }}"
    line: "{{ swap_file }} none swap sw 0 0"
  tags:
    - system.swap.fstab

- name: turn on swap
  command: swapon -a
  when: not swap_file_check.stat.exists
  tags:
    - system.swap.on

- name: set swapiness
  sysctl:
    name: vm.swappiness
    value: "1"
  tags:
    - system.swap.swappiness
